# Generated by Django 3.1.2 on 2020-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydroxychloroquine', '0004_auto_20201028_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(to='Hydroxychloroquine.Role'),
        ),
    ]
