# Generated by Django 3.1.3 on 2020-11-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hydroxychloroquine', '0005_auto_20201028_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hydroxychloroquine.report'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_last_on_campus',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_test',
            field=models.DateField(),
        ),
    ]
