# Generated by Django 3.1.2 on 2020-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydroxychloroquine', '0007_excursion_days_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[], default='STU', max_length=3),
        ),
    ]
