# Generated by Django 3.1.2 on 2020-12-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydroxychloroquine', '0008_auto_20201130_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='days_selected',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
