# Generated by Django 3.1.2 on 2020-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydroxychloroquine', '0009_auto_20201201_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_type',
            field=models.CharField(default='STU', max_length=3),
        ),
    ]
